# Generated by Django 5.0 on 2025-10-22 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_email_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_visibility', models.CharField(choices=[('public', 'Public - Visible to all recruiters'), ('private', 'Private - Only visible to you'), ('selective', 'Selective - Choose what to show')], default='public', help_text='Control who can see your profile', max_length=20)),
                ('show_email', models.BooleanField(default=True, help_text='Show email address to recruiters')),
                ('show_phone', models.BooleanField(default=True, help_text='Show phone number to recruiters')),
                ('show_location', models.BooleanField(default=True, help_text='Show location to recruiters')),
                ('show_bio', models.BooleanField(default=True, help_text='Show professional summary to recruiters')),
                ('show_skills', models.BooleanField(default=True, help_text='Show skills to recruiters')),
                ('show_work_experience', models.BooleanField(default=True, help_text='Show work experience to recruiters')),
                ('show_education', models.BooleanField(default=True, help_text='Show education to recruiters')),
                ('show_links', models.BooleanField(default=True, help_text='Show external links to recruiters')),
                ('show_profile_picture', models.BooleanField(default=True, help_text='Show profile picture to recruiters')),
                ('allow_contact', models.BooleanField(default=True, help_text='Allow recruiters to contact you directly')),
                ('contact_method', models.CharField(choices=[('email', 'Email only'), ('phone', 'Phone only'), ('both', 'Email and phone')], default='both', help_text='Preferred contact method', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to='profiles.profile')),
            ],
        ),
    ]
