# Generated by Django 5.0 on 2025-10-22 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profileprivacysettings'),
        ('profiles', '0003_userprofile'),
    ]

    operations = [
    ]
