# Generated by Django 5.0 on 2025-11-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_merge_0003_profileprivacysettings_0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='commute_radius',
            field=models.PositiveIntegerField(blank=True, help_text='Preferred commute radius in miles (e.g., 10 for 10 miles)', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for commute radius filtering', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for commute radius filtering', max_digits=9, null=True),
        ),
    ]
