# Generated by Django 5.2.8 on 2025-11-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_commute_radius_profile_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitude for commute radius filtering', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitude for commute radius filtering', max_digits=10, null=True),
        ),
    ]
