# Generated by Django 5.0 on 2025-10-23 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobapplication'),
        ('kanban', '0002_auto_create_pipeline_stages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='status',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='kanban_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_application', to='kanban.profilecard'),
        ),
    ]
