# Generated by Django 5.0 on 2025-10-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_jobapplication_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='_status',
            field=models.CharField(db_column='status', default='applied', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
