# Generated by Django 5.0 on 2025-10-23 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobapplication__status_jobapplication_updated_at'),
        ('kanban', '0002_auto_create_pipeline_stages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='_status',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Application Submitted'), ('review', 'Under Review'), ('interview', 'Interview Stage'), ('offer', 'Offer Received'), ('closed', 'Application Closed')], default='applied', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='kanban_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_link', to='kanban.profilecard'),
        ),
    ]
