# Generated by Django 5.0 on 2025-10-25 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_emailcommunication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailcommunication",
            name="job_application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emails",
                to="jobs.jobapplication",
            ),
        ),
    ]
