# Generated by Django 5.0 on 2025-11-22 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_job_latitude_job_longitude'),
        ('profiles', '0005_profile_commute_radius_profile_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCandidateSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this saved search', max_length=255)),
                ('search_query', models.CharField(blank=True, help_text='General search query', max_length=255)),
                ('skills', models.CharField(blank=True, help_text='Comma-separated list of required skills', max_length=512)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('min_years_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('education_level', models.CharField(blank=True, max_length=100)),
                ('notify_on_new_matches', models.BooleanField(default=True, help_text='Get notified when new candidates match this search')),
                ('notification_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Saved Candidate Searches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.DecimalField(decimal_places=2, help_text='Match score between 0 and 100', max_digits=5)),
                ('match_reason', models.TextField(blank=True, help_text='Explanation of why this candidate was recommended')),
                ('is_viewed', models.BooleanField(default=False)),
                ('is_contacted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_recommendations', to='profiles.profile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='jobs.job')),
            ],
            options={
                'ordering': ['-match_score', '-created_at'],
                'indexes': [models.Index(fields=['job', '-match_score'], name='jobs_jobrec_job_id_41b46e_idx'), models.Index(fields=['candidate_profile'], name='jobs_jobrec_candida_b0e547_idx')],
                'unique_together': {('job', 'candidate_profile')},
            },
        ),
        migrations.CreateModel(
            name='SearchNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('matched_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_notifications', to='profiles.profile')),
                ('saved_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='jobs.savedcandidatesearch')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('saved_search', 'matched_profile')},
            },
        ),
    ]
