# Generated by Django 5.2.8 on 2025-11-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_savedcandidatesearch_jobrecommendation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitude for location-based filtering', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitude for location-based filtering', max_digits=10, null=True),
        ),
    ]
