# Generated by Django 5.0 on 2025-10-23 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_jobapplication__status_jobapplication_status_and_more'),
        ('kanban', '0002_auto_create_pipeline_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecard',
            name='job_application',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_card', to='jobs.jobapplication'),
        ),
    ]
