# Generated by Django 5.0 on 2025-10-23 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_profilecard_job_application'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profilecard',
            unique_together=set(),
        ),
    ]
