# Generated by Django 5.2.6 on 2025-09-28 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_profile_email_profile_first_name_profile_last_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('profile_interest', 'Profile Interest'), ('resume_review', 'Resume Review'), ('interview', 'Interview'), ('hired', 'Hired'), ('rejected', 'Rejected')], max_length=50, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='#3498db', help_text='Hex color code for the stage', max_length=7)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='KanbanBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Hiring Pipeline', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_boards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, help_text='Position within the stage')),
                ('notes', models.TextField(blank=True, help_text='Recruiter notes about this candidate')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_cards', to='kanban.kanbanboard')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_cards', to='profiles.profile')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_cards', to='kanban.pipelinestage')),
            ],
            options={
                'ordering': ['stage__order', 'position'],
                'unique_together': {('board', 'profile')},
            },
        ),
        migrations.CreateModel(
            name='ProfileLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='profiles.profile')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('recruiter', 'profile')},
            },
        ),
    ]
